contact_click = "//a[normalize-space()='Contact']"
contact_email = "recipient-email"
contact_name = "recipient-name"
contact_message = "message-text"
contact_message_text = "We have been using this website and automating the same"
contact_send_message = "(//button[@type='button'])[3]"
contact_close = "(//button[@type='button'])[2]"

login_btn = "login2"
login_username = "loginusername"
login_password = "loginpassword"
account_text_username = "pythonlogic"
account_text_password = "pythonlogic"
login_close = "(//button[@type='button'])[8]"
account_login = "(//button[@type='button'])[9]"
laptops = "(//a[@class='list-group-item'])[3]"
sonyvaio = "(//*[@id='tbodyid']/div[1]/div/div/h4/a)"
addtocart = "(//*[@id='tbodyid']/div[2]/div/a)"
sony_laptop_name = "//*[@id='tbodyid']/h2"
cart_btn = "(//div//ul//li//a[contains(text(),'Cart')])"
delete_btn = "(//*[@id='tbodyid']/tr/td[4]/a)"
placeorder_btn = "(//*[@id='page-wrapper']/div/div[2]/button)"
name = "(//*[@id='name'])"
country = "(//*[@id='country'])"
city = "(//*[@id='city'])"
card = "(//*[@id='card'])"
month = "(//*[@id='month'])"
year = "(//*[@id='year'])"
purchase_btn = "(//*[@id='orderModal']/div/div/div[3]/button[2])"
okay_btn = "(/html/body/div[10]/div[7]/div/button)"
macbook = "(//*[@id='tbodyid']/div[3]/div/div/h4/a)"
addcart_btn = "(//*[@id='tbodyid']/div[2]/div/a)"
home = "//*[@id='navbarExample']/ul/li[1]/a"
logged_in_username = "(//a[@class='nav-link'])[7]"
logged_in_user_name_text = "Welcome pythonlogic"

signup_btn = "signin2"
signup_username = "sign-username"
signup_password = "sign-password"
signup_text_username = "pythonseeker"
signup_text_password = "pythonseeker"
signup_account = "(//button[@type='button'])[6]"
signup_close = "(//button[@type='button'])[5]"

home_btn = "(//a[contains(@class,'nav-link')])[1]"
home_next = "//button[@id='next2']"
home_previous = "prev2"
home_banner_forward_btn = "carousel-control-next-icon"
home_banner_backward_btn = "carousel-control-prev-icon"

wrong_cred_username = "9999"
wrong_cred_password = "9999"
wrong_cred_close = "btn btn-secondary"
# ph_locators
ph_product = "Samsung galaxy s6"
ph_add_to_cart_btn = "Add to cart"
cart_btn = "Cart"
place_order_btn = "//button[@class='btn btn-success']"
name_txt_field = "name"
country_txt_field = "country"
city_txt_field = "city"
card_txt_field = "card"
month_txt_field = "month"
year_txt_field = "year"
purchase_btn = "//div[@class='modal-footer']/button[text()='Purchase']"
confirmation_ok_btn = "//div[@class='sa-confirm-button-container']/button[text()='OK']"
