contact_click = "//a[normalize-space()='Contact']"
contact_email = "recipient-email"
contact_name = "recipient-name"
contact_message = "message-text"
contact_message_text = "We have been using this website and automating the same"
contact_send_message = "(//button[@type='button'])[3]"
contact_close = "(//button[@type='button'])[2]"
login_btn = "login2"
login_username = "loginusername"
login_password = "loginpassword"
account_text_username = "pythonlogic"
account_text_password = "pythonlogic"
login_close = "(//button[@type='button'])[8]"
account_login = "(//button[@type='button'])[9]"
