contact_click = "//a[normalize-space()='Contact']"
contact_email = "recipient-email"
contact_name = "recipient-name"
contact_message = "message-text"
contact_message_text = "We have been using this website and automating the same"
contact_send_message = "(//button[@type='button'])[3]"
contact_close = "(//button[@type='button'])[2]"

login_btn = "login2"
login_username = "loginusername"
login_password = "loginpassword"
account_text_username = "pythonlogic"
account_text_password = "pythonlogic"
login_close = "(//button[@type='button'])[8]"
account_login = "(//button[@type='button'])[9]"
logged_in_username = "(//a[@class='nav-link'])[7]"
logged_in_user_name_text = "Welcome pythonlogic"

signup_btn = "signin2"
signup_username = "sign-username"
signup_password = "sign-password"
signup_text_username = "pythonseeker"
signup_text_password = "pythonseeker"
signup_account = "(//button[@type='button'])[6]"
signup_close = "(//button[@type='button'])[5]"

home_btn = "(//a[contains(@class,'nav-link')])[1]"
home_next = "//button[@id='next2']"
home_previous = "prev2"
home_banner_forward_btn = "carousel-control-next-icon"
home_banner_backward_btn = "carousel-control-prev-icon"

wrong_cred_username= "shiva"
wrong_cred_password= "shiva"
